### ISSUE TITLE
Ability to show usage help on main

### ISSUE THREAD

**Issue by untitaker** [DasIch/argvard#2]
Currently argvard forces the user to define a main function, and do something useful in it. However, i have the situation where i can't do anything meaningful in main(), so i want to display the help there and exit with code 1. Currently i do this in main:

```
app.options['--help'].function(context)
```

but it would be nice to do this in a documented way. I see two options:

1.) define a default main function which does exactly that (in other words, don't force the user to define a main function)
2.) define an API for showing the help and exiting with code 1.
3.) Both.

**Comment by DasIch** [comment]
Fixed in 62b29c5c93ef0423bc9c4947366da8cbd770faa1 by calling `--help`, if no main function is defined.

In order to delegate to an option, you can do `context.caller.options['--help'].function(context)` which will call the `--help` function of `Argvard` instance or the last `command` invoked by the user, though I'm not sure I want to expose the `options` dictionary as public API by documenting it. However I'm considering adding an API, for invoking options/commands relative to the option/command called by argvard, see #3.

**Comment by untitaker** [comment]
Awesome, thanks!
